name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: windows
            extension: .exe
          - goos: linux
            extension: ""
          - goos: darwin
            extension: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/gitpulse-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}